#!/bin/bash

# DNS Diagnostic and Fix Script for EC2 Instance
# Run this script on your EC2 instance to diagnose and fix DNS issues

echo "=========================================="
echo "DNS Diagnostic and Fix Script"
echo "=========================================="
echo ""

# Check current DNS configuration
echo "1. Checking current DNS configuration..."
echo "----------------------------------------"
cat /etc/resolv.conf
echo ""

# Test DNS resolution
echo "2. Testing DNS resolution..."
echo "----------------------------------------"
echo "Testing smtp.gmail.com..."
if nslookup smtp.gmail.com > /dev/null 2>&1; then
    echo "✅ DNS resolution is working!"
    nslookup smtp.gmail.com | head -5
else
    echo "❌ DNS resolution failed!"
    echo ""
    echo "3. Attempting to fix DNS..."
    echo "----------------------------------------"
    
    # Backup current config
    sudo cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
    echo "✅ Backed up current resolv.conf"
    
    # Check if systemd-resolved is running
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        echo "Detected systemd-resolved, configuring..."
        sudo mkdir -p /etc/systemd/resolved.conf.d
        sudo tee /etc/systemd/resolved.conf.d/dns_servers.conf > /dev/null <<EOF
[Resolve]
DNS=8.8.8.8 8.8.4.4 1.1.1.1
EOF
        sudo systemctl restart systemd-resolved
        echo "✅ Configured systemd-resolved with Google DNS"
    else
        # For non-systemd systems, directly edit resolv.conf
        echo "Configuring /etc/resolv.conf directly..."
        sudo tee /etc/resolv.conf > /dev/null <<EOF
# DNS Configuration - Auto-generated by fix_dns.sh
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
EOF
        echo "✅ Updated /etc/resolv.conf with Google DNS"
    fi
    
    # Test again
    echo ""
    echo "4. Testing DNS resolution after fix..."
    echo "----------------------------------------"
    sleep 2
    if nslookup smtp.gmail.com > /dev/null 2>&1; then
        echo "✅ DNS resolution is now working!"
        nslookup smtp.gmail.com | head -5
    else
        echo "❌ DNS resolution still failing. Please check:"
        echo "   - VPC DNS settings in AWS Console"
        echo "   - Security group outbound rules (port 53)"
        echo "   - Network ACLs"
    fi
fi

echo ""
echo "5. Testing Python DNS resolution..."
echo "----------------------------------------"
python3 -c "
import socket
try:
    ip = socket.gethostbyname('smtp.gmail.com')
    print(f'✅ Python DNS resolution successful: smtp.gmail.com -> {ip}')
except Exception as e:
    print(f'❌ Python DNS resolution failed: {e}')
"

echo ""
echo "=========================================="
echo "Diagnostic complete!"
echo "=========================================="

